backend:
  name: github
  repo: l3n0ire/PEAR-Impact-Project
  branch: Grommet

publish_mode: editorial_workflow

media_folder: PEAR/static/images

collections:
  - name: "blog"
    label: "Stories"
    folder: "PEAR/src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    preview_path: "{{slug}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags }